/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mystock;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author air
 */
public class Fournisseur_Client extends javax.swing.JFrame {

    /**
     * Creates new form Fourniseur_Client
     */
    public Fournisseur_Client() {
        Connect();
        initComponents();
        loadFournisseur();
        loadClient();
        
        
    }
    Connection connection;
    PreparedStatement pst;
    PreparedStatement pst1;
    PreparedStatement pst2;

    DefaultTableModel df;
    
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        fourni = new javax.swing.JRadioButton();
        client = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomPrenomTxt = new javax.swing.JTextField();
        numTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adrTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        villeCombo = new javax.swing.JComboBox<>();
        ajouterBtn = new javax.swing.JButton();
        rechercheBtn = new javax.swing.JButton();
        modifierBtn = new javax.swing.JButton();
        supprimerBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        fourniTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rechrcheByCombo = new javax.swing.JComboBox<>();
        rechercheTxt = new javax.swing.JTextField();
        fermerProdBtn = new javax.swing.JButton();
        annulerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        buttonGroup1.add(fourni);
        fourni.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        fourni.setSelected(true);
        fourni.setText("Fournisseur");

        buttonGroup1.add(client);
        client.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        client.setText("Client");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel1.setText("Category :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel2.setText("Nom et Prenom :");

        nomPrenomTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        numTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel3.setText("N° telephone :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Adresse :");

        adrTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel5.setText("Ville :");

        villeCombo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        villeCombo.setForeground(new java.awt.Color(204, 0, 51));
        villeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adrar", "Aïn-Defla", "Aïn-Témouchent", "Alger", "Annaba", "Batna", "Béchar", "Béjaïa", "Biskra", "Blida", "Bordj-Bou-Arreridj", "Bouira", "Boumerdès", "Chlef", "Constantine", "Djelfa", "El-Bayadh", "El-Oued", "El-Taref", "Ghardaia", "Guelma", "Illizi", "Jijel", "Khenchela", "Laghouat", "M'Sila", "Mascara", "Médéa", "Mila", "Mostaganem", "Naâma", "Oran", "Ouargla", "Oum-El-Bouaghi", "Relizane", "Saida", "Sétif", "Sidi-Bel-Abbès", "Skikda", "Souk-Ahras", "Tamanrasset", "Tébessa", "Tiaret", "Tindouf", "Tipaza", "Tissemsilt", "Tizi-Ouzou", "Tlemcen" }));

        ajouterBtn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        ajouterBtn.setText("Ajouter");
        ajouterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtnActionPerformed(evt);
            }
        });

        rechercheBtn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        rechercheBtn.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/loupe.png")); // NOI18N
        rechercheBtn.setText("Rechercher");
        rechercheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheBtnActionPerformed(evt);
            }
        });

        modifierBtn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        modifierBtn.setText("Modifier");
        modifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBtnActionPerformed(evt);
            }
        });

        supprimerBtn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        supprimerBtn.setText("Supprimer");
        supprimerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("Id : ");

        idTxt.setEditable(false);
        idTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idTxt.setForeground(new java.awt.Color(255, 0, 0));

        clientTable.setBackground(new java.awt.Color(204, 255, 204));
        clientTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°client", "nom prenom", "N°telephone", "Adresse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientTable.setRowHeight(25);
        clientTable.setSelectionBackground(new java.awt.Color(0, 102, 255));
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientTable);

        fourniTable.setBackground(new java.awt.Color(204, 255, 204));
        fourniTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fourniTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°forn", "Nom Prenom", "N°telephone", "Adresse", "Ville"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fourniTable.setRowHeight(25);
        fourniTable.setSelectionBackground(new java.awt.Color(0, 102, 255));
        fourniTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourniTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(fourniTable);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("<html><u>Client</html></u>");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("<html><u>Fournisseur</html></u>");

        rechrcheByCombo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        rechrcheByCombo.setForeground(new java.awt.Color(204, 0, 51));
        rechrcheByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom_prenom", "Ville " }));

        rechercheTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        fermerProdBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fermerProdBtn.setText("Fermer");
        fermerProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerProdBtnActionPerformed(evt);
            }
        });

        annulerBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        annulerBtn.setText("Annuler");
        annulerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomPrenomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(89, 89, 89)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(villeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(client)
                                    .addComponent(fourni))
                                .addGap(352, 352, 352))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rechrcheByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rechercheTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(rechercheBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(ajouterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(modifierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(supprimerBtn)
                .addGap(71, 71, 71)
                .addComponent(annulerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fermerProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomPrenomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(villeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourni)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(client)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rechrcheByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rechercheTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rechercheBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supprimerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(annulerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(fermerProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Connection Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myStock", "root", "conan-kun");
            System.out.println("connected");
            return connection;

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("not connected");
            return null;
        }
    }
    public void loadFournisseur()
    {
        int a;
        try {
            pst = connection.prepareStatement("SELECT * FROM fournisseurs");
            ResultSet rs = pst.executeQuery();
        
            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            System.out.println("culomn number is "+ a);
            df = (DefaultTableModel)fourniTable.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i=0; i<=a; i++)
                {
                    v2.add(rs.getString("idfournisseurs"));
                    v2.add(rs.getString("nom_prenom"));
                    v2.add(rs.getString("N_telephone"));
                    v2.add(rs.getString("Adresse"));
                    v2.add(rs.getString("Ville"));
                  
                
                }
                df.addRow(v2);
            }
     
        } catch (SQLException ex) {
            Logger.getLogger(Fournisseur_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void loadClient()
    {
        int a;
        try {
            pst = connection.prepareStatement("SELECT * FROM clients");
            ResultSet rs = pst.executeQuery();
        
            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            System.out.println("culomn number is "+ a);
            df = (DefaultTableModel)clientTable.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i=0; i<=a; i++)
                {
                    v2.add(rs.getString("idclients"));
                    v2.add(rs.getString("nom_prenom"));
                    v2.add(rs.getString("N_telephone"));
                    v2.add(rs.getString("Adresse"));
                    v2.add(rs.getString("Ville"));
                  
                
                }
                df.addRow(v2);
            }
     
        } catch (SQLException ex) {
            Logger.getLogger(Fournisseur_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void fourniTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourniTableMouseClicked
        int i;

        i= fourniTable.getSelectedRow();

        idTxt.setText( fourniTable.getValueAt(i, 0)+"");
        nomPrenomTxt.setText( fourniTable.getValueAt(i, 1)+"");
        numTxt.setText( fourniTable.getValueAt(i, 2)+"");
        adrTxt.setText( fourniTable.getValueAt(i, 3)+"");
         ajouterBtn.setEnabled(false);
    }//GEN-LAST:event_fourniTableMouseClicked

    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked
         int i;

        i= clientTable.getSelectedRow();
         System.out.println("i="+i);
        idTxt.setText( clientTable.getValueAt(i, 0)+"");
        nomPrenomTxt.setText( clientTable.getValueAt(i, 1)+"");
        numTxt.setText( clientTable.getValueAt(i, 2)+"");
        adrTxt.setText( clientTable.getValueAt(i, 3)+"");
        ajouterBtn.setEnabled(false);

    }//GEN-LAST:event_clientTableMouseClicked

    private void ajouterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtnActionPerformed
         if(fourni.isSelected()){
             try {

            String nom_prenom = nomPrenomTxt.getText();
            String tel = numTxt.getText();
            String adr = adrTxt.getText();
            String ville  = (String) villeCombo.getSelectedItem();
            
            // TODO add your handling code here:

            pst = connection.prepareStatement("INSERT INTO `fournisseurs`( `nom_prenom`, `N_telephone`, `Adresse`,`Ville`) values(?,?,?,?)");
            pst.setString(1, nom_prenom);
            pst.setString(2, tel);
            pst.setString(3, adr);
            pst.setString(4, ville);
          
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Fournisseur a ete bien ajoute");
             idTxt.setText("");
            nomPrenomTxt.setText("");
            numTxt.setText("");
            adrTxt.setText("");
            villeCombo.setSelectedIndex(1);

            nomPrenomTxt.requestFocus();
            loadFournisseur();
            
            
 
        } catch (SQLException ex) {
            Logger.getLogger(Fournisseur_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
         else {
              try {

            String nom_prenom = nomPrenomTxt.getText();
            String tel = numTxt.getText();
            String adr = adrTxt.getText();
            String ville  = (String) villeCombo.getSelectedItem();
            
            // TODO add your handling code here:

            pst = connection.prepareStatement("INSERT INTO `clients`( `nom_prenom`, `N_telephone`, `Adresse`,`Ville`) values(?,?,?,?)");
            pst.setString(1, nom_prenom);
            pst.setString(2, tel);
            pst.setString(3, adr);
            pst.setString(4, ville);
          
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Client a ete bien ajoute");
             idTxt.setText("");
            nomPrenomTxt.setText("");
            numTxt.setText("");
            adrTxt.setText("");
            villeCombo.setSelectedIndex(1);

            nomPrenomTxt.requestFocus();
            loadClient();
            
            
 
        } catch (SQLException ex) {
            Logger.getLogger(Fournisseur_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
    }//GEN-LAST:event_ajouterBtnActionPerformed

    private void supprimerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBtnActionPerformed
       if(fourni.isSelected()){
             try {

        df =  (DefaultTableModel)fourniTable.getModel();
        int selected = fourniTable.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        
            pst = connection.prepareStatement("DELETE FROM fournisseurs WHERE idfournisseurs = ?");

            pst.setInt(1, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "fournisseur a ete bien supprime");

            idTxt.setText("");
            nomPrenomTxt.setText("");
            numTxt.setText("");
            adrTxt.setText("");
            villeCombo.setSelectedIndex(1);

            nomPrenomTxt.requestFocus();  
            loadFournisseur();
            ajouterBtn.setEnabled(true);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "ereur operation");
        }
       }
       else {
            try {

        df =  (DefaultTableModel)clientTable.getModel();
        int selected = clientTable.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        
            pst = connection.prepareStatement("DELETE FROM clients WHERE idclients = ?");

            pst.setInt(1, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Client a ete bien supprime");

            idTxt.setText("");
            nomPrenomTxt.setText("");
            numTxt.setText("");
            adrTxt.setText("");
            villeCombo.setSelectedIndex(1);
            nomPrenomTxt.requestFocus();  
            loadClient();
            ajouterBtn.setEnabled(true);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "ereur operation");
        }
       }
     
    }//GEN-LAST:event_supprimerBtnActionPerformed

    private void annulerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerBtnActionPerformed
        idTxt.setText("");
        nomPrenomTxt.setText("");
        numTxt.setText("");
        adrTxt.setText("");
        rechercheTxt.setText("");
        villeCombo.setSelectedIndex(0);
        

        nomPrenomTxt.requestFocus();
        loadClient();
        loadFournisseur();
        ajouterBtn.setEnabled(true);
    }//GEN-LAST:event_annulerBtnActionPerformed

    private void modifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBtnActionPerformed
       if(fourni.isSelected()){
           try {
        df = (DefaultTableModel) fourniTable.getModel();
        int selected = fourniTable.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

        String nom_prenom = nomPrenomTxt.getText();
            String tel = numTxt.getText();
            String adr = adrTxt.getText();
            String ville  = (String) villeCombo.getSelectedItem();

    
            pst = connection.prepareStatement("Update fournisseurs set nom_prenom = ?, N_telephone =?, Adresse =?, Ville=? where idfournisseurs =?");
            pst.setString(1, nom_prenom);
            pst.setString(2, tel);
            pst.setString(3, adr);
            pst.setString(4, ville);
            pst.setInt(5, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "fournisseur updated");
         idTxt.setText("");
        nomPrenomTxt.setText("");
        numTxt.setText("");
        adrTxt.setText("");
        villeCombo.setSelectedIndex(1);

        nomPrenomTxt.requestFocus();
        loadFournisseur();
        nomPrenomTxt.setEnabled(true);
            fourniTable.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ereur operation");
        } 
       } else {
            try {
           df = (DefaultTableModel) clientTable.getModel();
        int selected = clientTable.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

        String nom_prenom = nomPrenomTxt.getText();
            String tel = numTxt.getText();
            String adr = adrTxt.getText();
            String ville  = (String) villeCombo.getSelectedItem();

       

            pst = connection.prepareStatement("Update clients set nom_prenom = ?, N_telephone =?, Adresse =?, Ville=? where idclients =?");
            pst.setString(1, nom_prenom);
            pst.setString(2, tel);
            pst.setString(3, adr);
            pst.setString(4, ville);
            pst.setInt(5, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "client updated");
         idTxt.setText("");
        nomPrenomTxt.setText("");
        numTxt.setText("");
        adrTxt.setText("");
        villeCombo.setSelectedIndex(1);

        nomPrenomTxt.requestFocus();
        loadClient();
        nomPrenomTxt.setEnabled(true);
        fourniTable.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ereur operation");
        } 
           
       }
    }//GEN-LAST:event_modifierBtnActionPerformed

    private void fermerProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerProdBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_fermerProdBtnActionPerformed

    private void rechercheBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheBtnActionPerformed
        if (fourni.isSelected()) {
            try {
                int a;
                String word = (String) rechrcheByCombo.getSelectedItem();
                String recherche = rechercheTxt.getText();

                pst = connection.prepareStatement("SELECT * FROM fournisseurs WHERE " + word + " like '" + recherche + "%' ");
                rs = pst.executeQuery();
                ResultSetMetaData rd = rs.getMetaData();
                a = rd.getColumnCount();
                System.out.println("culomn number is " + a);
                df = (DefaultTableModel) fourniTable.getModel();
                df.setRowCount(0);
                while (rs.next()) {
                    Vector v2 = new Vector();
                    for (int i = 0; i <= a; i++) {
                        v2.add(rs.getString("idfournisseurs"));
                        v2.add(rs.getString("nom_prenom"));
                        v2.add(rs.getString("N_telephone"));
                        v2.add(rs.getString("Adresse"));
                        v2.add(rs.getString("Ville"));

                    }
                    df.addRow(v2);
                }

           } catch (SQLException ex) {
            Logger.getLogger(Fournisseur_Client.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex + " error in recuperation");
        }
         }
        else {
             try {
                int a;
                String word = (String) rechrcheByCombo.getSelectedItem();
                String recherche = rechercheTxt.getText();

                pst = connection.prepareStatement("SELECT * FROM clients WHERE " + word + " like '" + recherche + "%' ");
                rs = pst.executeQuery();
                ResultSetMetaData rd = rs.getMetaData();
                a = rd.getColumnCount();
                System.out.println("culomn number is " + a);
                df = (DefaultTableModel) clientTable.getModel();
                df.setRowCount(0);
                while (rs.next()) {
                    Vector v2 = new Vector();
                    for (int i = 0; i <= a; i++) {
                        v2.add(rs.getString("idclients"));
                        v2.add(rs.getString("nom_prenom"));
                        v2.add(rs.getString("N_telephone"));
                        v2.add(rs.getString("Adresse"));
                        v2.add(rs.getString("Ville"));

                    }
                    df.addRow(v2);
                }

           } catch (SQLException ex) {
            Logger.getLogger(Fournisseur_Client.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex + " error in recuperation");
        }
        }
    }//GEN-LAST:event_rechercheBtnActionPerformed
                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fournisseur_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fournisseur_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fournisseur_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fournisseur_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fournisseur_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adrTxt;
    private javax.swing.JButton ajouterBtn;
    private javax.swing.JButton annulerBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton client;
    private javax.swing.JTable clientTable;
    private javax.swing.JButton fermerProdBtn;
    private javax.swing.JRadioButton fourni;
    private javax.swing.JTable fourniTable;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifierBtn;
    private javax.swing.JTextField nomPrenomTxt;
    private javax.swing.JTextField numTxt;
    private javax.swing.JButton rechercheBtn;
    private javax.swing.JTextField rechercheTxt;
    private javax.swing.JComboBox<String> rechrcheByCombo;
    private javax.swing.JButton supprimerBtn;
    private javax.swing.JComboBox<String> villeCombo;
    // End of variables declaration//GEN-END:variables
}
