/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mystock;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author air
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        vendeurBtn = new javax.swing.JButton();
        produitsBtn = new javax.swing.JButton();
        achatsBtn = new javax.swing.JButton();
        ventesBtn = new javax.swing.JButton();
        SortirBtn = new javax.swing.JButton();
        stateBtn = new javax.swing.JButton();
        FournisseurClientBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        titleLabel.setText("MyStock");

        vendeurBtn.setBackground(new java.awt.Color(204, 255, 204));
        vendeurBtn.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 18)); // NOI18N
        vendeurBtn.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/employee.png")); // NOI18N
        vendeurBtn.setText("Vendeurs");
        vendeurBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendeurBtnActionPerformed(evt);
            }
        });

        produitsBtn.setBackground(new java.awt.Color(204, 255, 204));
        produitsBtn.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 18)); // NOI18N
        produitsBtn.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/box.png")); // NOI18N
        produitsBtn.setText("Produits");
        produitsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitsBtnActionPerformed(evt);
            }
        });

        achatsBtn.setBackground(new java.awt.Color(204, 255, 204));
        achatsBtn.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 18)); // NOI18N
        achatsBtn.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/checklist.png")); // NOI18N
        achatsBtn.setText(" Achats");
        achatsBtn.setMaximumSize(new java.awt.Dimension(78, 23));
        achatsBtn.setMinimumSize(new java.awt.Dimension(78, 23));
        achatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                achatsBtnActionPerformed(evt);
            }
        });

        ventesBtn.setBackground(new java.awt.Color(204, 255, 204));
        ventesBtn.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 18)); // NOI18N
        ventesBtn.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/sales.png")); // NOI18N
        ventesBtn.setText("Ventes");
        ventesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventesBtnActionPerformed(evt);
            }
        });

        SortirBtn.setBackground(new java.awt.Color(204, 255, 204));
        SortirBtn.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 18)); // NOI18N
        SortirBtn.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/cancel.png")); // NOI18N
        SortirBtn.setText("Sortir");
        SortirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortirBtnActionPerformed(evt);
            }
        });

        stateBtn.setBackground(new java.awt.Color(204, 255, 204));
        stateBtn.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 18)); // NOI18N
        stateBtn.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/sale-report.png")); // NOI18N
        stateBtn.setText("Statistique");
        stateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateBtnActionPerformed(evt);
            }
        });

        FournisseurClientBtn.setBackground(new java.awt.Color(204, 255, 204));
        FournisseurClientBtn.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 18)); // NOI18N
        FournisseurClientBtn.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/temporary-agency.png")); // NOI18N
        FournisseurClientBtn.setText("<html>Fournisseur    &<br>Clients</html>");
        FournisseurClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FournisseurClientBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ventesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FournisseurClientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vendeurBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(achatsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(produitsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(titleLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(SortirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(produitsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(achatsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(stateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vendeurBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(ventesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(FournisseurClientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(SortirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FournisseurClientBtn, achatsBtn, produitsBtn, stateBtn, vendeurBtn, ventesBtn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vendeurBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendeurBtnActionPerformed
        vendeur v = new vendeur();
        v.setVisible(true);
    }//GEN-LAST:event_vendeurBtnActionPerformed

    private void produitsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitsBtnActionPerformed
        produits p = new produits();
        p.setVisible(true);
    }//GEN-LAST:event_produitsBtnActionPerformed

    private void achatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_achatsBtnActionPerformed
        Achats a = new Achats();
        a.setVisible(true);
    }//GEN-LAST:event_achatsBtnActionPerformed

    private void ventesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventesBtnActionPerformed
        Ventes vente = new Ventes();
        vente.setVisible(true);
    }//GEN-LAST:event_ventesBtnActionPerformed

    private void SortirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortirBtnActionPerformed
         System.exit(0);
    }//GEN-LAST:event_SortirBtnActionPerformed

    private void stateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateBtnActionPerformed
      XYSeries s = new XYSeries("data");
      getStats x = new getStats();
      try {
          s.add(1 , x.Jan());
          s.add(2 , x.Fev());
          s.add(3 , x.Mars());
          s.add(4 , x.Avril());
          s.add(5 , x.mai());
          s.add(6 , x.Juin());
          s.add(7 , x.Juillet());
          s.add(8 , x.Aout());
          s.add(9 , x.Septembre());
          s.add(10 , x.Octobre());
          s.add(11 , x.Nov());
          s.add(12 , x.Dec());
         
      } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
      XYSeriesCollection dataset = new XYSeriesCollection(s);
      JFreeChart ch = ChartFactory.createXYBarChart("Flux de Revenue", "Mois", false , "Revenue", dataset, PlotOrientation.VERTICAL, false, false, false);
      ChartFrame frame = new ChartFrame("Statistique" , ch);
      frame.pack();
      frame.setVisible(true);
    }//GEN-LAST:event_stateBtnActionPerformed

    private void FournisseurClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FournisseurClientBtnActionPerformed
          Fournisseur_Client fc = new Fournisseur_Client();
          fc.setVisible(true);
    }//GEN-LAST:event_FournisseurClientBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FournisseurClientBtn;
    private javax.swing.JButton SortirBtn;
    private javax.swing.JButton achatsBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton produitsBtn;
    private javax.swing.JButton stateBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton vendeurBtn;
    private javax.swing.JButton ventesBtn;
    // End of variables declaration//GEN-END:variables
}
