/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mystock;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author air
 */
public class InfoLoginChange extends javax.swing.JFrame {

    /**
     * Creates new form InfoLoginChange
     */
    public InfoLoginChange() {
        initComponents();
        Connect();
    }
     Connection connection;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nmTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        psTxt = new javax.swing.JPasswordField();
        fermerBtn = new javax.swing.JButton();
        modifierBtn = new javax.swing.JButton();
        annulerBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nouveau nom utilisateur :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 160, -1, -1));

        nmTxt.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        nmTxt.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(nmTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 180, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nouveau mot de passe :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, -1));

        psTxt.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        psTxt.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(psTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 180, -1));

        fermerBtn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        fermerBtn.setText("Fermer");
        fermerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(fermerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, 47));

        modifierBtn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        modifierBtn.setText("modifier");
        modifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBtnActionPerformed(evt);
            }
        });
        jPanel1.add(modifierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 331, 170, 47));

        annulerBtn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        annulerBtn.setText("annuler");
        annulerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(annulerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/air/NetBeansProjects/myStock/src/main/java/com/mycompany/mystock/images/Two-factor-authentication.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Connection Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myStock", "root", "conan-kun");
            System.out.println("connected");
            return connection;

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("not connected");
            return null;
        }
    }
    private void fermerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_fermerBtnActionPerformed

    private void modifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBtnActionPerformed
        String user = nmTxt.getText();
        String passw = psTxt.getText();
        try {
            pst = connection.prepareStatement("UPDATE users set user = ?, password =? where idusers =1");
             pst.setString(1, user);
            pst.setString(2, passw);
             pst.executeUpdate();
             JOptionPane.showMessageDialog(this, "la modification est bien réussie");
        } catch (Exception e) {
             Logger.getLogger(produits.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "erreur, verifier les donnes");
        }
        
        nmTxt.setText("");
        psTxt.setText("");
  
    }//GEN-LAST:event_modifierBtnActionPerformed

    private void annulerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerBtnActionPerformed
        nmTxt.setText("");
        psTxt.setText("");
        nmTxt.requestFocus();
    }//GEN-LAST:event_annulerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoLoginChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoLoginChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoLoginChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoLoginChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoLoginChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerBtn;
    private javax.swing.JButton fermerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifierBtn;
    private javax.swing.JTextField nmTxt;
    private javax.swing.JPasswordField psTxt;
    // End of variables declaration//GEN-END:variables
}
