/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mystock;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author air
 */
public class produits extends javax.swing.JFrame {

    /**
     * Creates new form produits
     */
    public produits() {
        initComponents();
        Connect();
        load();
    }
    Connection connection;
    PreparedStatement pst;
    DefaultTableModel df;
    
    public Connection Connect()
    {
        try{     
         Class.forName("com.mysql.jdbc.Driver");
          connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myStock", "root", "conan-kun"); 
         System.out.println("connected");
         return connection ;

            }catch(Exception e)
            { 
                e.printStackTrace();
                System.out.println("not connected");
                return null;
            }  
    }
    
    public void load()
    {
        int a;
        try {
            pst = connection.prepareStatement("SELECT * FROM product");
            ResultSet rs = pst.executeQuery();
        
            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            System.out.println("culomn number is "+ a);
            df = (DefaultTableModel)produitTable.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i=0; i<=a; i++)
                {
                    v2.add(rs.getString("idProduit"));
                    v2.add(rs.getString("pname"));
                    v2.add(rs.getString("description"));
                    v2.add(rs.getString("barcode"));
                    v2.add(rs.getString("prix_achat"));
                    v2.add(rs.getString("prix_vente"));
                    v2.add(rs.getString("quantite"));                       
                }
                df.addRow(v2);
            }
     
        } catch (SQLException ex) {
            Logger.getLogger(produits.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnameTxt = new javax.swing.JTextField();
        desnameTxt = new javax.swing.JTextField();
        barcnameTxt = new javax.swing.JTextField();
        prix_achatTxt = new javax.swing.JTextField();
        prix_venteTxt = new javax.swing.JTextField();
        quantiteTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        produitTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        annulerProdBtn = new javax.swing.JButton();
        addProdBtn = new javax.swing.JButton();
        modifierProdBtn = new javax.swing.JButton();
        fermerProdBtn = new javax.swing.JButton();
        suppProdBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><u>Ajouter Produit</u></html>", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Nom produit :");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Descreption :");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Barcode :");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Prix d'achat :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Prix de vente :");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Quantite :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(desnameTxt)
                    .addComponent(barcnameTxt)
                    .addComponent(prix_achatTxt)
                    .addComponent(prix_venteTxt)
                    .addComponent(quantiteTxt))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prix_achatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prix_venteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(quantiteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        produitTable.setBackground(new java.awt.Color(204, 255, 204));
        produitTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        produitTable.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        produitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ProduitID", "Nom Produit", "Descreption", "Barcode", "Prix achat", "Prix vente", "Quantite"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produitTable.setRowHeight(30);
        produitTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produitTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(produitTable);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel7.setText("Liste des Produits");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        annulerProdBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        annulerProdBtn.setText("Annuler");
        annulerProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerProdBtnActionPerformed(evt);
            }
        });

        addProdBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addProdBtn.setText("Ajouter");
        addProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdBtnActionPerformed(evt);
            }
        });

        modifierProdBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        modifierProdBtn.setText("Modifier");
        modifierProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierProdBtnActionPerformed(evt);
            }
        });

        fermerProdBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        fermerProdBtn.setText("Fermer");
        fermerProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerProdBtnActionPerformed(evt);
            }
        });

        suppProdBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        suppProdBtn.setText("Supprimer");
        suppProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppProdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(addProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(modifierProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(suppProdBtn)
                .addGap(115, 115, 115)
                .addComponent(annulerProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(fermerProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifierProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suppProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annulerProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fermerProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerProdBtnActionPerformed
         this.setVisible(false);
    }//GEN-LAST:event_fermerProdBtnActionPerformed

    private void produitTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produitTableMouseClicked
int selected = produitTable.getSelectedRow();
       
         int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
         pnameTxt.setText(df.getValueAt(selected, 1).toString());
        desnameTxt.setText(df.getValueAt(selected,2).toString());
         barcnameTxt.setText(df.getValueAt(selected, 3).toString());
         prix_achatTxt.setText(df.getValueAt(selected, 4).toString());
         prix_venteTxt.setText(df.getValueAt(selected, 5).toString());
         quantiteTxt.setText(df.getValueAt(selected, 6).toString());
         pnameTxt.requestFocus();
         
         addProdBtn.setEnabled(false);    }//GEN-LAST:event_produitTableMouseClicked

    private void suppProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppProdBtnActionPerformed
        df =  (DefaultTableModel)produitTable.getModel();
        int selected = produitTable.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

        try {

            pst = connection.prepareStatement("DELETE FROM product WHERE idProduit = ?");

            pst.setInt(1, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Vendeur a ete bien supprime");

            pnameTxt.setText("");
            desnameTxt.setText("");
            barcnameTxt.setText("");
            prix_achatTxt.setText("");
            prix_venteTxt.setText("");
            quantiteTxt.setText("");
            pnameTxt.requestFocus();
            load();
            addProdBtn.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(produits.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_suppProdBtnActionPerformed

    private void modifierProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierProdBtnActionPerformed
        df = (DefaultTableModel) produitTable.getModel();
        int selected = produitTable.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

        String pname = pnameTxt.getText();
        String des = desnameTxt.getText();
        String barcode = barcnameTxt.getText();
        String prix_achat  = prix_achatTxt.getText();
        String prix_vente  = prix_venteTxt.getText();
        String quantite  = quantiteTxt.getText();

        try {

            pst = connection.prepareStatement("UPDATE product set pname = ?, description =?, barcode =?, prix_achat=?, prix_vente=?, quantite=? where idProduit =?");
            pst.setString(1, pname);
            pst.setString(2, des);
            pst.setString(3, barcode);
            pst.setString(4, prix_achat);
            pst.setString(5, prix_vente);
            pst.setString(6, quantite);
            pst.setInt(7, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Produit updated");

            pnameTxt.setText("");
            desnameTxt.setText("");
            barcnameTxt.setText("");
            prix_achatTxt.setText("");
            prix_venteTxt.setText("");
            quantiteTxt.setText("");
            pnameTxt.requestFocus();
            load();
            produitTable.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(produits.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modifierProdBtnActionPerformed

    private void annulerProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerProdBtnActionPerformed
        pnameTxt.setText("");
        desnameTxt.setText("");
        barcnameTxt.setText("");
        prix_achatTxt.setText("");
        prix_venteTxt.setText("");
        quantiteTxt.setText("");

        pnameTxt.requestFocus();
        load();
        addProdBtn.setEnabled(true);
    }//GEN-LAST:event_annulerProdBtnActionPerformed

    private void addProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdBtnActionPerformed
        try {

            String pname = pnameTxt.getText();
            String des = desnameTxt.getText();
            String barcode = barcnameTxt.getText();
            String prix_achat  = prix_achatTxt.getText();
            String prix_vente  = prix_venteTxt.getText();
            String quantite  = quantiteTxt.getText();

            // TODO add your handling code here:

            pst = connection.prepareStatement("INSERT INTO product(pname,description,barcode,prix_achat,prix_vente,quantite)values(?,?,?,?,?,?)");
            pst.setString(1, pname);
            pst.setString(2, des);
            pst.setString(3, barcode);
            pst.setString(4, prix_achat);
            pst.setString(5, prix_vente);
            pst.setString(6, quantite);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Produit a ete bien ajoute");

            pnameTxt.setText("");
            desnameTxt.setText("");
            barcnameTxt.setText("");
            prix_achatTxt.setText("");
            prix_venteTxt.setText("");
            quantiteTxt.setText("");

            pnameTxt.requestFocus();
            load();

        } catch (SQLException ex) {
            Logger.getLogger(produits.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addProdBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProdBtn;
    private javax.swing.JButton annulerProdBtn;
    private javax.swing.JTextField barcnameTxt;
    private javax.swing.JTextField desnameTxt;
    private javax.swing.JButton fermerProdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifierProdBtn;
    private javax.swing.JTextField pnameTxt;
    private javax.swing.JTextField prix_achatTxt;
    private javax.swing.JTextField prix_venteTxt;
    private javax.swing.JTable produitTable;
    private javax.swing.JTextField quantiteTxt;
    private javax.swing.JButton suppProdBtn;
    // End of variables declaration//GEN-END:variables
}
