/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mystock;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author air
 */
public class vendeur extends javax.swing.JFrame {

    /**
     * Creates new form vendeur
     */
    public vendeur() {
        initComponents();
        Connect();
        load();
    }
    Connection connection;
    PreparedStatement pst;
    DefaultTableModel df;

    public Connection Connect()
    {
        try{  
         Class.forName("com.mysql.jdbc.Driver");
          connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myStock", "root", "conan-kun"); 
         System.out.println("connected");
         return connection ;

            }catch(Exception e)
            { 
                e.printStackTrace();
                System.out.println("not connected");
                return null;
            }  
    }
    
     public void load()
    {
        int a;
        try {
            pst = connection.prepareStatement("SELECT * FROM vendor");
            ResultSet rs = pst.executeQuery();
        
            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
           // System.out.println("culomn number is "+ a);
            df = (DefaultTableModel)tableVendor.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i=0; i<=a; i++)
                {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("name"));
                    v2.add(rs.getString("phone"));
                    v2.add(rs.getString("email"));
                    v2.add(rs.getString("address"));                 
                }
                df.addRow(v2);
            }
     
        } catch (SQLException ex) {
            Logger.getLogger(vendeur.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomLbl = new javax.swing.JLabel();
        telLbl = new javax.swing.JLabel();
        adrLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        nomTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        adrtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVendor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        modifierBtn = new javax.swing.JButton();
        supBtn = new javax.swing.JButton();
        annulerBtn = new javax.swing.JButton();
        fermerBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(970, 535));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><u>Nouveau vendeur</html></u>", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        nomLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nomLbl.setText("Nom :");

        telLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        telLbl.setText("Telephone :");

        adrLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        adrLbl.setText("E-mail :");

        emailLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emailLbl.setText("Adresse :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomLbl)
                    .addComponent(emailLbl)
                    .addComponent(adrLbl)
                    .addComponent(telLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(nomTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adrtxt))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adrtxt, emailTxt, nomTxt, telTxt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomLbl)
                    .addComponent(nomTxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telLbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adrLbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLbl))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adrtxt, emailTxt, nomTxt, telTxt});

        tableVendor.setBackground(new java.awt.Color(204, 255, 204));
        tableVendor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableVendor.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tableVendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "VendeurID", "Vendeur Nom", "Telephone", "E-mail", "Adresse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVendor.setRowHeight(30);
        tableVendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVendorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVendor);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        addBtn.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        addBtn.setText("Ajouter");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        modifierBtn.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        modifierBtn.setText("Modifier");
        modifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBtnActionPerformed(evt);
            }
        });

        supBtn.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        supBtn.setText("Supprimer");
        supBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supBtnActionPerformed(evt);
            }
        });

        annulerBtn.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        annulerBtn.setText("Annuler");
        annulerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerBtnActionPerformed(evt);
            }
        });

        fermerBtn.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        fermerBtn.setText("Fermer");
        fermerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(modifierBtn)
                .addGap(60, 60, 60)
                .addComponent(supBtn)
                .addGap(60, 60, 60)
                .addComponent(annulerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(fermerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBtn, annulerBtn, modifierBtn, supBtn});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fermerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annulerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des Vendeurs");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

                  String vname = nomTxt.getText();
                  String phone = telTxt.getText();
                  String email = emailTxt.getText();
                  String address = adrtxt.getText();
                  
        try {
            pst = connection.prepareStatement("INSERT INTO vendor(name,phone,email,address)values(?,?,?,?)");
            pst.setString(1, vname);
            pst.setString(2, phone);
            pst.setString(3, email);
            pst.setString(4, address);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "vendeur a ete bien ajoute");
            
            nomTxt.setText("");
             telTxt.setText("");
             emailTxt.setText("");
             adrtxt.setText("");
             nomTxt.requestFocus();
             load();
             
        } catch (SQLException ex) {
            Logger.getLogger(vendeur.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_addBtnActionPerformed

    private void modifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBtnActionPerformed
        df = (DefaultTableModel) tableVendor.getModel();
        int selected = tableVendor.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

        String vname = nomTxt.getText();
        String phone = telTxt.getText();
        String email = emailTxt.getText();
        String address = adrtxt.getText();

        try {

            pst = connection.prepareStatement("UPDATE vendor set name = ?, phone =?, email =?, address=? where id =?");
            pst.setString(1, vname);
            pst.setString(2, phone);
            pst.setString(3, email);
            pst.setString(4, address);
            pst.setInt(5, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Vendor Updated");

            nomTxt.setText("");
            telTxt.setText("");
            emailTxt.setText("");
            adrtxt.setText("");
            nomTxt.requestFocus();
            load();
            tableVendor.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(vendeur.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_modifierBtnActionPerformed

    private void annulerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerBtnActionPerformed
             nomTxt.setText("");
             telTxt.setText("");
             emailTxt.setText("");
             adrtxt.setText("");
             nomTxt.requestFocus();
             load();
              addBtn.setEnabled(true);
    }//GEN-LAST:event_annulerBtnActionPerformed

    private void fermerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_fermerBtnActionPerformed

    private void tableVendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVendorMouseClicked
        // TODO add your handling code here: df =  (DefaultTableModel)jTable1.getModel();
       int selected = tableVendor.getSelectedRow();
       
         int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
         nomTxt.setText(df.getValueAt(selected, 1).toString());
        telTxt.setText(df.getValueAt(selected,2).toString());
         emailTxt.setText(df.getValueAt(selected, 3).toString());
         adrtxt.setText(df.getValueAt(selected, 4).toString());
         
         addBtn.setEnabled(false);
         
    }//GEN-LAST:event_tableVendorMouseClicked

    private void supBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supBtnActionPerformed
         df =  (DefaultTableModel)tableVendor.getModel();
         int selected = tableVendor.getSelectedRow();
       
         int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        
   
        try {
            
            pst = connection.prepareStatement("DELETE FROM vendor WHERE id = ?");
           
            pst.setInt(1, id);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Vendeur a ete bien supprime");
            
             nomTxt.setText("");
             telTxt.setText("");
             emailTxt.setText("");
             adrtxt.setText("");
             nomTxt.requestFocus();
             load();
              addBtn.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(vendeur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_supBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendeur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel adrLbl;
    private javax.swing.JTextField adrtxt;
    private javax.swing.JButton annulerBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton fermerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifierBtn;
    private javax.swing.JLabel nomLbl;
    private javax.swing.JTextField nomTxt;
    private javax.swing.JButton supBtn;
    private javax.swing.JTable tableVendor;
    private javax.swing.JLabel telLbl;
    private javax.swing.JTextField telTxt;
    // End of variables declaration//GEN-END:variables
}
